### PR TITLE
Fix packages version pin for Debian, fix CI badge

### LINKED ISSUE #220: Version of mongo packages doesn't fix for Debian platforms
### Cookbook version
2.0.0

### Chef-client version
14.10.9

### Platform Details
Ubuntu 18.04 / Vagrant

### Scenario:
There is a problem in install recipe for Debian platform. 
In this line, the version attribute is defined. But, as stated in the Chef documentation, if you use package resource with multiple packages, you should use array.
https://docs.chef.io/resource_package.html chapter `Multiple Packages`

### Steps to Reproduce:
* Set version attribute `default['mongodb']['package_version'] = '3.6.9'`
* Run converge
* You will get this this result:
```
$ dpkg -l | grep mongo
ii  mongodb-org                      3.6.9                              amd64        MongoDB open source document-oriented database system (metapackage)
ii  mongodb-org-mongos               3.6.10                             amd64        MongoDB sharded cluster query router
ii  mongodb-org-server               3.6.9                              amd64        MongoDB database server
ii  mongodb-org-shell                3.6.9                              amd64        MongoDB shell client
ii  mongodb-org-tools                3.6.10                             amd64        MongoDB tools
```
So the server package will be installed with the right version, others will use latest 3.6.x

### Expected Result:
All packages will be installed with a fixed version

### Actual Result:
Only first one from list uses a fixed version, others are installed with latest from branch.

### Example recipe that you can apply locally with chef-apply test.rb

like in cookbook (not work)
```
deb_pkgs = [
  'mongodb-org-server',
  'mongodb-org-shell',
  'mongodb-org-tools',
  'mongodb-org-mongos',
]

package deb_pkgs do
  options '-o Dpkg::Options::="--force-confold" --force-yes'
  action :install
  version [ '3.6.9', '3.6.9', '3.6.9', '3.6.9']
end
```

worked one
```
deb_pkgs = [
  'mongodb-org-server',
  'mongodb-org-shell',
  'mongodb-org-tools',
  'mongodb-org-mongos',
]

package deb_pkgs do
  options '-o Dpkg::Options::="--force-confold" --force-yes'
  action :install
  version '3.6.9'
end
```

### PR DESCRIPTION
**Pull request by Nklya**
## Description

Fix packages version pin for Debian, more info in #220 issue.

### Issues Resolved

Fixes #220, #221 

### Check List
- [x] All tests pass. See https://github.com/sous-chefs/apache2/blob/master/TESTING.md
- [x] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable (not applicable)

P.S. Also it would be nice to update cookbook in the Supermarket. There is only the 1.2.0 version.

### CODE REVIEW

**Comment by kitchen-porter** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This Pull Request is probably missing tests.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by Nklya** [comment]
CI fails with error definitely not related to my changes. Could you please review why?

```
$ chef exec delivery local all
Chef Delivery
Running Every Stage
Running Lint Phase
/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/rubocop-0.62.0/lib/rubocop/target_finder.rb:103: warning: Insecure world writable dir /usr/local/bundle in PATH, mode 042777
Inspecting 48 files
```

File: recipes/install.rb [hunk 1]
```diff
@@ -130,7 +130,7 @@
   package deb_pkgs do
     options node['mongodb']['packager_options']
     action :install
-    version package_version
+    version [ package_version, package_version, package_version, package_version ]
```
Comment (josephholsten) [inline recipes/install.rb]: what on earth is happening here?

Comment (Nklya) [reply recipes/install.rb]: It fixes the version of every package.
Now it works only for the first one.
All described in issue 
https://github.com/sous-chefs/mongodb/issues/220

Comment (Nklya) [reply recipes/install.rb]: Check documentation https://docs.chef.io/resource_package.html `chapter Multiple Packages`

Comment (josephholsten) [reply recipes/install.rb]: ugh, and that's why I never use that "feature". It would be one thing if there was a `deb_pkg_versions` variable that actually matched up.

How do you feel about:
```ruby
  deb_pkg_suffixes = %w(
    server
    shell
    tools
    mongos
  )
  deb_pkg_suffixes.each do |suffix|
    package "#{node['mongodb']['package_name']}-#{suffix}" do
      options node['mongodb']['packager_options']
      action :install
      version package_version
      not_if { node['mongodb']['install_method'] == 'none' }
    end
  end
```

Is that worse? Or just differently terrible?

Comment (Nklya) [reply recipes/install.rb]: I think it's better. I will commit changes now, thanks.

**Comment by josephholsten** [comment]
ok, well the rubocop build warning is fixed in #223, but there's a whole lot of these errors in the next phase:

```
Recipe Compile Error in /tmp/d20190304-163-1huem31/cookbooks/sc-mongodb/recipes/default.rb
================================================================================

NoMethodError
-------------
undefined method `params' for nil:NilClass

Cookbook Trace:
---------------
  /tmp/d20190304-163-1huem31/cookbooks/sc-mongodb/recipes/default.rb:33:in `from_file'

Relevant File Content:
----------------------
/tmp/d20190304-163-1huem31/cookbooks/sc-mongodb/recipes/default.rb:

 26:  # allow mongodb_instance to run if recipe isn't included
 27:  allow_mongodb_instance_run = true
 28:  conflicting_recipes = %w(sc-mongodb::replicaset sc-mongodb::shard sc-mongodb::configserver sc-mongodb::mongos sc-mongodb::mms_agent)
 29:  conflicting_recipes.each do |recipe|
 30:    allow_mongodb_instance_run &&= false if node.run_context.loaded_recipe?(recipe)
 31:  end
 32:  
 33>> mongodb_instance node['mongodb']['instance_name']['mongod'] do
 34:    mongodb_type 'mongod'
 35:    only_if { allow_mongodb_instance_run }
 36:  end
 37:  
```

Details live in https://circleci.com/gh/sous-chefs/mongodb/88

Is this cookbook running correctly on your systems?

**Comment by Nklya** [comment]
Yes, we use it for simple one node setup on Ubuntu and Debian systems.
And the only thing that was annoying me is that packages were installed with different versions.

**Comment by josephholsten** [comment]
to any other reviewers, diff is cleaner without whitespace: https://github.com/sous-chefs/mongodb/pull/222/files?w=1

File: recipes/install.rb (hunk 1 above)
Comment (Nklya) [reply recipes/install.rb]: Thank you @josephholsten for pointing me to a better solution!
I've committed changes and tested them locally.

P.S. I used this strange solution before just because wanted to fix my problem and didn't think about little refactoring.

**Comment by scopenco** [comment]
👍 LGTM
