### PR TITLE
Reconverge

### LINKED ISSUE #179: rs_member_ips is referenced but not initialized
Variable `rs_member_ips` is referenced before it's set anywhere. Fist use is: https://github.com/sous-chefs/mongodb/blob/0b168a740a15435b1a2567f66add79beba4c625f/libraries/mongodb.rb#L134

The regression was most probably caused by 6f3f2caa88e7ee350f4be60a06d618d817c1d44e

### PR DESCRIPTION
**Pull request by swalberg**
Handle problems where reconverging constantly thinks the cluster has changed. This was happening because the test for a change didn't include default options whereas the server's response had default options, so the configs never matched. Thanks to Andy from the community slack, I came up with some code to compare only the necessary options.

Fixed a problem that appears only in TK where `*.vagrantup.com` hosts are ignored, but still processed later on.

Also re-implemented the `rs_member_ips` that was removed in 6f3f2ca and fixes #179. 

As a result of this, test kitchen replica tests run again:
```
sean~/play/mongodb (reconverge *)$ chef exec kitchen verify replicaset3-centos-73
-----> Starting Kitchen (v1.19.2)
-----> Setting up <replicaset3-centos-73>...
       Finished setting up <replicaset3-centos-73> (0m0.00s).
-----> Verifying <replicaset3-centos-73>...
       Detected alternative framework tests for `inspec`
       Loaded tests from {:path=>".Users.sean.play.mongodb.test.integration.replicaset3.inspec"}

Profile: tests from {:path=>"/Users/sean/play/mongodb/test/integration/replicaset3/inspec"} (tests from {:path=>".Users.sean.play.mongodb.test.integration.replicaset3.inspec"})
Version: (not specified)
Target:  ssh://vagrant@127.0.0.1:2202


  Service mongod
     ✔  should be installed
     ✔  should be enabled
     ✔  should be running
  Bash command
     ✔  mongo --eval "rs.status()" | grep name | wc -l exit_status should eq 0
     ✔  mongo --eval "rs.status()" | grep name | wc -l stdout should match "3"
  Bash command
     ✔  mongo --eval "rs.status()" exit_status should eq 0
     ✔  mongo --eval "rs.status()" stdout should match /.*^connecting to: test\n\{\n\t{1}"set" : "kitchen"\,$.*/
     ✔  mongo --eval "rs.status()" stdout should match /.*^\t{3}"_id" : 0\,\n\t{3}"name" : "mongo1:27017"\,$.*/
     ✔  mongo --eval "rs.status()" stdout should match /.*^\t{3}"_id" : 1\,\n\t{3}"name" : "mongo2:27017"\,$.*/
     ✔  mongo --eval "rs.status()" stdout should match /.*^\t{3}"_id" : 2\,\n\t{3}"name" : "mongo3:27017"\,$.*/

Test Summary: 10 successful, 0 failures, 0 skipped
       Finished verifying <replicaset3-centos-73> (0m0.52s).
```

### CODE REVIEW

File: libraries/mongodb.rb [hunk 1]
```diff
@@ -84,13 +93,14 @@ def self.configure_replicaset(node, name, members)
       return
     end
 
+    Chef::Log.info("#{members.map(&:fqdn).join(', ')}")
```
Comment (devsibwarra) [inline libraries/mongodb.rb]: Please update this to explain what is being dumped to avoid confusion when reviewing the output of a full Chef run

Comment (swalberg) [reply libraries/mongodb.rb]: Oh I'll actually delete that, I don't think it's needed.

**Comment by damacus** [comment]
lgtm 👍

**Comment by swalberg** [comment]
Thank you!
